# Generated by Django 4.1.5 on 2023-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.grade_and_section",
            ),
        ),
        migrations.AddField(
            model_name="exams",
            name="max_marks",
            field=models.IntegerField(default=None),
        ),
    ]
