# Generated by Django 4.1.5 on 2023-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_is_student_user_is_tecaher_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub1", models.IntegerField()),
                ("sub2", models.IntegerField()),
            ],
            options={
                "permissions": [
                    ("can_add_marks", "Can add data"),
                    ("can_view_marks", "Can view data"),
                ],
            },
        ),
    ]
