# Generated by Django 4.1.5 on 2023-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_marks"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
