# Generated by Django 4.1.5 on 2023-01-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student", models.CharField(max_length=254)),
                ("Date", models.DateField()),
                ("Morning", models.BooleanField()),
                ("Afternoon", models.BooleanField()),
                ("Percentage", models.CharField(max_length=254)),
            ],
        ),
    ]
